# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FuncTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.FuncTextBox.setGeometry(QtCore.QRect(30, 50, 231, 41))
        self.FuncTextBox.setObjectName("FuncTextBox")

        self.Flabel = QtWidgets.QLabel(self.centralwidget)
        self.Flabel.setGeometry(QtCore.QRect(40, 20, 120, 13))
        self.Flabel.setMinimumSize(QtCore.QSize(0, 0))
        self.Flabel.setObjectName("Flabel")


        self.MinLabel = QtWidgets.QLabel(self.centralwidget)
        self.MinLabel.setGeometry(QtCore.QRect(60, 150, 47, 13))
        self.MinLabel.setObjectName("MinLabel")

        self.MinTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.MinTextBox.setGeometry(QtCore.QRect(30, 180, 81, 41))
        self.MinTextBox.setObjectName("MinTextBox")


        self.MaxLabel = QtWidgets.QLabel(self.centralwidget)
        self.MaxLabel.setGeometry(QtCore.QRect(200, 150, 47, 13))
        self.MaxLabel.setObjectName("MaxLabel")



        self.MaxTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.MaxTextBox.setGeometry(QtCore.QRect(170, 180, 81, 41))
        self.MaxTextBox.setObjectName("MaxTextBox")

        self.plotButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotButton.setGeometry(QtCore.QRect(90, 290, 91, 41))
        self.plotButton.setObjectName("plotButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FuncTextBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Flabel.setText(_translate("MainWindow", "Function"))
        self.MinLabel.setText(_translate("MainWindow", "Min"))
        self.MaxLabel.setText(_translate("MainWindow", "Max"))
        self.MaxLabel.setFont(16)

        self.plotButton.setText(_translate("MainWindow", "Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
